# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 4);
user_pref("browser.dom.window.dump.enabled", true);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 24);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.safebrowsing.provider.0.gethashURL", "http://localhost/safebrowsing-dummy/gethash");
user_pref("browser.safebrowsing.provider.0.updateURL", "http://localhost/safebrowsing-dummy/update");
user_pref("browser.search.isUS", true);
user_pref("browser.sessionstore.resume_from_crash", false);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20150113033800");
user_pref("browser.slowStartup.averageTime", 4385);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage", "about:blank");
user_pref("browser.startup.homepage_override.buildID", "20150113033800");
user_pref("browser.startup.homepage_override.mstone", "35.0");
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"downloads-button\",\"home-button\",\"loop-button-throttled\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":3,\"newElementCount\":0}");
user_pref("browser.warnOnQuit", false);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1421521346974");
user_pref("datareporting.policy.firstRunTime", "1421434946973");
user_pref("datareporting.sessions.current.activeTicks", 3);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 2629);
user_pref("datareporting.sessions.current.main", 159);
user_pref("datareporting.sessions.current.startTime", "1421435734001");
user_pref("datareporting.sessions.current.totalTime", 17);
user_pref("datareporting.sessions.currentIndex", 4);
user_pref("datareporting.sessions.previous.0", "{\"s\":1421434944447,\"a\":3,\"t\":27,\"c\":true,\"m\":59,\"fp\":5298,\"sr\":5753}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1421434975837,\"a\":4,\"t\":21,\"c\":true,\"m\":115,\"fp\":3484,\"sr\":3806}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1421435051549,\"a\":4,\"t\":20,\"c\":true,\"m\":68,\"fp\":3603,\"sr\":3956}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1421435720728,\"a\":0,\"t\":11,\"c\":false,\"m\":69,\"fp\":3972,\"sr\":4298}");
user_pref("devtools.chrome.enabled", true);
user_pref("devtools.debugger.remote-enabled", true);
user_pref("devtools.errorconsole.enabled", true);
user_pref("devtools.inspector.showUserAgentStyles", true);
user_pref("devtools.profiler.ui.show-platform-data", true);
user_pref("devtools.telemetry.tools.opened.version", "{\"DEVTOOLS_JSBROWSERDEBUGGER_OPENED_PER_USER_FLAG\":\"35.0\",\"DEVTOOLS_TOOLBOX_OPENED_PER_USER_FLAG\":\"35.0\",\"DEVTOOLS_JSDEBUGGER_OPENED_PER_USER_FLAG\":\"35.0\",\"DEVTOOLS_WEBCONSOLE_OPENED_PER_USER_FLAG\":\"35.0\"}");
user_pref("extensions.autoDisableScopes", 10);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.blocklist.url", "http://localhost/extensions-dummy/blocklistURL");
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.checkCompatibility.35.0", false);
user_pref("extensions.checkCompatibility.nightly", false);
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:35.0");
user_pref("extensions.enabledScopes", 5);
user_pref("extensions.getAddons.cache.enabled", false);
user_pref("extensions.installDistroAddons", false);
user_pref("extensions.lastAppVersion", "35.0");
user_pref("extensions.lastPlatformVersion", "35.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.sdk.console.logLevel", "info");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.experiment.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.update.enabled", false);
user_pref("extensions.update.notifyUser", false);
user_pref("extensions.update.url", "http://localhost/extensions-dummy/updateURL");
user_pref("extensions.webservice.discoverURL", "http://localhost/extensions-dummy/discoveryURL");
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"35.0\",\"st\":1421249025000,\"mt\":1421121440000}}}");
user_pref("gecko.buildID", "20150113033800");
user_pref("gecko.mstone", "35.0");
user_pref("loop.soft_start_ticket_number", 1465092);
user_pref("loop.throttled2", false);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("startup.homepage_welcome_url", "about:blank");
user_pref("toolkit.startup.last_success", 1421435734);
user_pref("toolkit.telemetry.previousBuildID", "20150113033800");
user_pref("urlclassifier.updateinterval", 172800);
