#!/bin/bash

# update-url should never change, update the file to reflect new xpi versions
# update-link should always point to the newest 'release' on github

# Two files are generated by this command, the .xpi should be uploaded with a github release as a binary
# the .rdf should become the new update.rdf

# $1 argument should be the version (2015.2.24) of the software, is injected to the URL

cfx xpi --update-url https://raw.githubusercontent.com/ctag/chevaline_alpha/master/firefox/update.rdf \
--update-link https://github.com/ctag/chevaline_alpha/releases/download/$1/chevaline_alpha.xpi
